### ISSUE TITLE
Version 2.2.0

### ISSUE THREAD

**Issue by valendesigns** [valendesigns/option-tree#213]
Starting an issue to keep track of what's left to do for the 2.2.0 release.
- [x] WP 3.8 UI Fixes via https://github.com/valendesigns/option-tree/issues/210
- [x] Add an On/Off option type
- [x] Add Gallery option type
- [x] Add background-size to the Background option type
- [x] Add additional filters to the Theme Options UI array
- [x] Filter `get_categories()` in each option type
- [x] Fix broken localization directory path in theme mode via https://github.com/valendesigns/option-tree/issues/200
- [x] Make the OptionTree icon a font for use in WP 3.8 & fix the alignment in sidebar
- [x] Switch to the default WordPress Colorpicker
- [x] Conditional Toggling of Setting Fields via https://github.com/valendesigns/option-tree/pull/198
- [x] Subfolder compatibility via https://github.com/valendesigns/option-tree/pull/188
- [x] Possibly add an option description filter (needs more discussion) via https://github.com/valendesigns/option-tree/issues/161
- [x] Cannot save metabox text field value as 0 via https://github.com/valendesigns/option-tree/issues/177
- [x] Fix bug caused by using 'home_url' when loading dynamic CSS files.
- [x] Add fallback text when displaying posts without titles in various option types.
