### ISSUE TITLE
Feature Version 2.3.0

### ISSUE THREAD

**Issue by valendesigns** [valendesigns/option-tree#217]
Issue tracker for 2.3.0
- [x] Add support for a RTL stylesheet & create actions after enqueue_styles/scripts. https://github.com/valendesigns/option-tree/issues/208
- [x] Support for sub sections in both the UI Builder and array mode. https://github.com/valendesigns/option-tree/issues/215
- [x] Date picker. https://github.com/valendesigns/option-tree/issues/116
- [x] Figure out a way to have theme options on a per theme basis. https://github.com/valendesigns/option-tree/issues/100
- [x] CSS editor to support tab spacing, line numbers, and syntax highlighting. https://github.com/valendesigns/option-tree/issues/218
- [x] Add theme mode installation instructions to readme.txt https://github.com/valendesigns/option-tree/issues/226
- [x] Add filter to list item Title https://github.com/valendesigns/option-tree/issues/228
- [x] Update the UI to support WP 3.8 color schemes
- [x] Add a logo and version filter to the Theme Option page https://github.com/valendesigns/option-tree/issues/232
- [x] Allow "Send to OptionTree" text to be filtered. https://github.com/valendesigns/option-tree/issues/249
- [x] Composer Integration https://github.com/valendesigns/option-tree/pull/248
- [x] Add custom CSS classes to the wrapping container. https://github.com/valendesigns/option-tree/issues/236
- [x] Merge 2.2.3 into the codebase.
- [x] Support I18n text domains in the exported `theme-options.php` file.
- [x] Fixed a bug that kept the UI from displaying when using the `ot_type_background_size_choices` filter.
