### ISSUE TITLE
Feature Version 2.4.0

### ISSUE THREAD

**Issue by valendesigns** [valendesigns/option-tree#252]
Issue tracker for 2.4.0
- [x] Merge the `feature-postformats` branch. Turns on via the `ot_post_formats` filter which is set to `false` by default.
- [x] Make it possible to use the attachment ID instead of the GUID. #112 & #308
- [x] Social Media Links Option Type #263
- [x] CSS option type is not working in metabox anymore. #301
- [x] More options in the line-height (typography) #320
- [x] Meta Box Min-Height when using Tabs in Meta Boxes #312 
- [x] Two Conditions #282 
- [x] Meta Box Drag & Drop Issue #306 
- [x] use php realpath to load language info #291 
- [x] Simple filter making dynamic select fields possible #298 
- [x] add meta box wrap class #288 
- [x] fix search order of contains condition string #295 
- [x] Remove mysql functions #297 
- [x] allow translation of option types #304
- [x] Fix the left padding/margin of labels in metabox list items.
- [x] Update code sample to include OptionTree from a theme to avoid errors wh... #300
- [x] Display a nag when a file is overwriting the UI Builder #313 & #253  
- [x] OptionTree Theme 2.4.0 #322 
- [x] Clean up conditionals JS and add keyup event.
- [x] WooCommerce: Tabs doesn't render properly #325
